/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BucketList } from "./BucketList";
export * as factories from "./factories";
export { BucketList__factory } from "./factories/BucketList__factory";
